/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtthanManagerLoginRouteImport } from './routes/utthan-manager-login'
import { Route as UtthanCoachingOrganizationsRouteImport } from './routes/utthan-coaching-organizations'
import { Route as UtthanCoachingRegistrationRouteImport } from './routes/utthan-coaching-registration'
import { Route as TalentFelicitationCeremonyRouteImport } from './routes/talent-felicitation-ceremony'
import { Route as SpgbpRouteImport } from './routes/spgbp'
import { Route as SuccessStoriesStorySlugRouteImport } from './routes/success-stories.$storySlug'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as SbgbpManagerLoginRouteImport } from './routes/sbgbp-manager-login'
import { Route as SammanSamarohRegistrationRouteImport } from './routes/samman-samaroh-registration'
import { Route as PatrikaRouteImport } from './routes/patrika'
import { Route as MemberLoginRouteImport } from './routes/member-login'
import { Route as MediaRouteImport } from './routes/media'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CsrPartnershipRouteImport } from './routes/csr-partnership'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArticlesArticleSlugRouteImport } from './routes/articles.$articleSlug'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AavedanFormRouteImport } from './routes/aavedan-form'
import { Route as IndexRouteImport } from './routes/index'

const UtthanManagerLoginRoute = UtthanManagerLoginRouteImport.update({
  id: '/utthan-manager-login',
  path: '/utthan-manager-login',
  getParentRoute: () => rootRouteImport,
} as any)
const UtthanCoachingOrganizationsRoute =
  UtthanCoachingOrganizationsRouteImport.update({
    id: '/utthan-coaching-organizations',
    path: '/utthan-coaching-organizations',
    getParentRoute: () => rootRouteImport,
  } as any)
const UtthanCoachingRegistrationRoute =
  UtthanCoachingRegistrationRouteImport.update({
    id: '/utthan-coaching-registration',
    path: '/utthan-coaching-registration',
    getParentRoute: () => rootRouteImport,
  } as any)
const TalentFelicitationCeremonyRoute =
  TalentFelicitationCeremonyRouteImport.update({
    id: '/talent-felicitation-ceremony',
    path: '/talent-felicitation-ceremony',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpgbpRoute = SpgbpRouteImport.update({
  id: '/spgbp',
  path: '/spgbp',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesStorySlugRoute =
  SuccessStoriesStorySlugRouteImport.update({
    id: '/success-stories/$storySlug',
    path: '/success-stories/$storySlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SbgbpManagerLoginRoute = SbgbpManagerLoginRouteImport.update({
  id: '/sbgbp-manager-login',
  path: '/sbgbp-manager-login',
  getParentRoute: () => rootRouteImport,
} as any)
const SammanSamarohRegistrationRoute =
  SammanSamarohRegistrationRouteImport.update({
    id: '/samman-samaroh-registration',
    path: '/samman-samaroh-registration',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatrikaRoute = PatrikaRouteImport.update({
  id: '/patrika',
  path: '/patrika',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberLoginRoute = MemberLoginRouteImport.update({
  id: '/member-login',
  path: '/member-login',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CsrPartnershipRoute = CsrPartnershipRouteImport.update({
  id: '/csr-partnership',
  path: '/csr-partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticleSlugRoute = ArticlesArticleSlugRouteImport.update({
  id: '/articles/$articleSlug',
  path: '/articles/$articleSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AavedanFormRoute = AavedanFormRouteImport.update({
  id: '/aavedan-form',
  path: '/aavedan-form',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aavedan-form': typeof AavedanFormRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/admin-login': typeof AdminLoginRoute
  '/articles/$articleSlug': typeof ArticlesArticleSlugRoute
  '/articles': typeof ArticlesRoute
  '/contact': typeof ContactRoute
  '/csr-partnership': typeof CsrPartnershipRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/media': typeof MediaRoute
  '/member-login': typeof MemberLoginRoute
  '/patrika': typeof PatrikaRoute
  '/samman-samaroh-registration': typeof SammanSamarohRegistrationRoute
  '/sbgbp-manager-login': typeof SbgbpManagerLoginRoute
  '/success-stories/$storySlug': typeof SuccessStoriesStorySlugRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/spgbp': typeof SpgbpRoute
  '/talent-felicitation-ceremony': typeof TalentFelicitationCeremonyRoute
  '/utthan-coaching-organizations': typeof UtthanCoachingOrganizationsRoute
  '/utthan-coaching-registration': typeof UtthanCoachingRegistrationRoute
  '/utthan-manager-login': typeof UtthanManagerLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aavedan-form': typeof AavedanFormRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/admin-login': typeof AdminLoginRoute
  '/articles/$articleSlug': typeof ArticlesArticleSlugRoute
  '/articles': typeof ArticlesRoute
  '/contact': typeof ContactRoute
  '/csr-partnership': typeof CsrPartnershipRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/media': typeof MediaRoute
  '/member-login': typeof MemberLoginRoute
  '/patrika': typeof PatrikaRoute
  '/samman-samaroh-registration': typeof SammanSamarohRegistrationRoute
  '/sbgbp-manager-login': typeof SbgbpManagerLoginRoute
  '/success-stories/$storySlug': typeof SuccessStoriesStorySlugRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/spgbp': typeof SpgbpRoute
  '/talent-felicitation-ceremony': typeof TalentFelicitationCeremonyRoute
  '/utthan-coaching-organizations': typeof UtthanCoachingOrganizationsRoute
  '/utthan-coaching-registration': typeof UtthanCoachingRegistrationRoute
  '/utthan-manager-login': typeof UtthanManagerLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aavedan-form': typeof AavedanFormRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/admin-login': typeof AdminLoginRoute
  '/articles/$articleSlug': typeof ArticlesArticleSlugRoute
  '/articles': typeof ArticlesRoute
  '/contact': typeof ContactRoute
  '/csr-partnership': typeof CsrPartnershipRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/media': typeof MediaRoute
  '/member-login': typeof MemberLoginRoute
  '/patrika': typeof PatrikaRoute
  '/samman-samaroh-registration': typeof SammanSamarohRegistrationRoute
  '/sbgbp-manager-login': typeof SbgbpManagerLoginRoute
  '/success-stories/$storySlug': typeof SuccessStoriesStorySlugRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/spgbp': typeof SpgbpRoute
  '/talent-felicitation-ceremony': typeof TalentFelicitationCeremonyRoute
  '/utthan-coaching-organizations': typeof UtthanCoachingOrganizationsRoute
  '/utthan-coaching-registration': typeof UtthanCoachingRegistrationRoute
  '/utthan-manager-login': typeof UtthanManagerLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aavedan-form'
    | '/about'
    | '/activities'
    | '/admin-login'
    | '/articles/$articleSlug'
    | '/articles'
    | '/contact'
    | '/csr-partnership'
    | '/donate'
    | '/gallery'
    | '/media'
    | '/member-login'
    | '/patrika'
    | '/samman-samaroh-registration'
    | '/sbgbp-manager-login'
    | '/success-stories/$storySlug'
    | '/success-stories'
    | '/spgbp'
    | '/talent-felicitation-ceremony'
    | '/utthan-coaching-organizations'
    | '/utthan-coaching-registration'
    | '/utthan-manager-login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aavedan-form'
    | '/about'
    | '/activities'
    | '/admin-login'
    | '/articles/$articleSlug'
    | '/articles'
    | '/contact'
    | '/csr-partnership'
    | '/donate'
    | '/gallery'
    | '/media'
    | '/member-login'
    | '/patrika'
    | '/samman-samaroh-registration'
    | '/sbgbp-manager-login'
    | '/success-stories/$storySlug'
    | '/success-stories'
    | '/spgbp'
    | '/talent-felicitation-ceremony'
    | '/utthan-coaching-organizations'
    | '/utthan-coaching-registration'
    | '/utthan-manager-login'
  id:
    | '__root__'
    | '/'
    | '/aavedan-form'
    | '/about'
    | '/activities'
    | '/admin-login'
    | '/articles/$articleSlug'
    | '/articles'
    | '/contact'
    | '/csr-partnership'
    | '/donate'
    | '/gallery'
    | '/media'
    | '/member-login'
    | '/patrika'
    | '/samman-samaroh-registration'
    | '/sbgbp-manager-login'
    | '/success-stories/$storySlug'
    | '/success-stories'
    | '/spgbp'
    | '/talent-felicitation-ceremony'
    | '/utthan-coaching-organizations'
    | '/utthan-coaching-registration'
    | '/utthan-manager-login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AavedanFormRoute: typeof AavedanFormRoute
  AboutRoute: typeof AboutRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ArticlesArticleSlugRoute: typeof ArticlesArticleSlugRoute
  ArticlesRoute: typeof ArticlesRoute
  ContactRoute: typeof ContactRoute
  CsrPartnershipRoute: typeof CsrPartnershipRoute
  DonateRoute: typeof DonateRoute
  GalleryRoute: typeof GalleryRoute
  MediaRoute: typeof MediaRoute
  MemberLoginRoute: typeof MemberLoginRoute
  PatrikaRoute: typeof PatrikaRoute
  SammanSamarohRegistrationRoute: typeof SammanSamarohRegistrationRoute
  SbgbpManagerLoginRoute: typeof SbgbpManagerLoginRoute
  SuccessStoriesStorySlugRoute: typeof SuccessStoriesStorySlugRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  SpgbpRoute: typeof SpgbpRoute
  TalentFelicitationCeremonyRoute: typeof TalentFelicitationCeremonyRoute
  UtthanCoachingOrganizationsRoute: typeof UtthanCoachingOrganizationsRoute
  UtthanCoachingRegistrationRoute: typeof UtthanCoachingRegistrationRoute
  UtthanManagerLoginRoute: typeof UtthanManagerLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utthan-manager-login': {
      id: '/utthan-manager-login'
      path: '/utthan-manager-login'
      fullPath: '/utthan-manager-login'
      preLoaderRoute: typeof UtthanManagerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utthan-coaching-organizations': {
      id: '/utthan-coaching-organizations'
      path: '/utthan-coaching-organizations'
      fullPath: '/utthan-coaching-organizations'
      preLoaderRoute: typeof UtthanCoachingOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utthan-coaching-registration': {
      id: '/utthan-coaching-registration'
      path: '/utthan-coaching-registration'
      fullPath: '/utthan-coaching-registration'
      preLoaderRoute: typeof UtthanCoachingRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-felicitation-ceremony': {
      id: '/talent-felicitation-ceremony'
      path: '/talent-felicitation-ceremony'
      fullPath: '/talent-felicitation-ceremony'
      preLoaderRoute: typeof TalentFelicitationCeremonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spgbp': {
      id: '/spgbp'
      path: '/spgbp'
      fullPath: '/spgbp'
      preLoaderRoute: typeof SpgbpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sbgbp-manager-login': {
      id: '/sbgbp-manager-login'
      path: '/sbgbp-manager-login'
      fullPath: '/sbgbp-manager-login'
      preLoaderRoute: typeof SbgbpManagerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories/$storySlug': {
      id: '/success-stories/$storySlug'
      path: '/success-stories/$storySlug'
      fullPath: '/success-stories/$storySlug'
      preLoaderRoute: typeof SuccessStoriesStorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samman-samaroh-registration': {
      id: '/samman-samaroh-registration'
      path: '/samman-samaroh-registration'
      fullPath: '/samman-samaroh-registration'
      preLoaderRoute: typeof SammanSamarohRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrika': {
      id: '/patrika'
      path: '/patrika'
      fullPath: '/patrika'
      preLoaderRoute: typeof PatrikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-login': {
      id: '/member-login'
      path: '/member-login'
      fullPath: '/member-login'
      preLoaderRoute: typeof MemberLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csr-partnership': {
      id: '/csr-partnership'
      path: '/csr-partnership'
      fullPath: '/csr-partnership'
      preLoaderRoute: typeof CsrPartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$articleSlug': {
      id: '/articles/$articleSlug'
      path: '/articles/$articleSlug'
      fullPath: '/articles/$articleSlug'
      preLoaderRoute: typeof ArticlesArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aavedan-form': {
      id: '/aavedan-form'
      path: '/aavedan-form'
      fullPath: '/aavedan-form'
      preLoaderRoute: typeof AavedanFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AavedanFormRoute: AavedanFormRoute,
  AboutRoute: AboutRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdminLoginRoute: AdminLoginRoute,
  ArticlesArticleSlugRoute: ArticlesArticleSlugRoute,
  ArticlesRoute: ArticlesRoute,
  ContactRoute: ContactRoute,
  CsrPartnershipRoute: CsrPartnershipRoute,
  DonateRoute: DonateRoute,
  GalleryRoute: GalleryRoute,
  MediaRoute: MediaRoute,
  MemberLoginRoute: MemberLoginRoute,
  PatrikaRoute: PatrikaRoute,
  SammanSamarohRegistrationRoute: SammanSamarohRegistrationRoute,
  SbgbpManagerLoginRoute: SbgbpManagerLoginRoute,
  SuccessStoriesStorySlugRoute: SuccessStoriesStorySlugRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  SpgbpRoute: SpgbpRoute,
  TalentFelicitationCeremonyRoute: TalentFelicitationCeremonyRoute,
  UtthanCoachingOrganizationsRoute: UtthanCoachingOrganizationsRoute,
  UtthanCoachingRegistrationRoute: UtthanCoachingRegistrationRoute,
  UtthanManagerLoginRoute: UtthanManagerLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
